// Code generated by ogen, DO NOT EDIT.
package openapi

type CreateBillRes interface {
	createBillRes()
}

type CreateCompanyRes interface {
	createCompanyRes()
}

type GetBillsRes interface {
	getBillsRes()
}

type GetCompanyNameRes interface {
	getCompanyNameRes()
}

type LoginRes interface {
	loginRes()
}

type RegisterUserRes interface {
	registerUserRes()
}
