// Code generated by ogen, DO NOT EDIT.

package openapi

type CompanyResponse struct {
	ID          ID          `json:"id"`
	Name        Name        `json:"name"`
	CreditLimit CreditLimit `json:"credit_limit"`
}

// GetID returns the value of ID.
func (s *CompanyResponse) GetID() ID {
	return s.ID
}

// GetName returns the value of Name.
func (s *CompanyResponse) GetName() Name {
	return s.Name
}

// GetCreditLimit returns the value of CreditLimit.
func (s *CompanyResponse) GetCreditLimit() CreditLimit {
	return s.CreditLimit
}

// SetID sets the value of ID.
func (s *CompanyResponse) SetID(val ID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *CompanyResponse) SetName(val Name) {
	s.Name = val
}

// SetCreditLimit sets the value of CreditLimit.
func (s *CompanyResponse) SetCreditLimit(val CreditLimit) {
	s.CreditLimit = val
}

func (*CompanyResponse) createCompanyRes() {}

// Ref: #/components/schemas/ConflictError
type ConflictError struct {
	Error   OptString `json:"error"`
	Message OptString `json:"message"`
}

// GetError returns the value of Error.
func (s *ConflictError) GetError() OptString {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() OptString {
	return s.Message
}

// SetError sets the value of Error.
func (s *ConflictError) SetError(val OptString) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val OptString) {
	s.Message = val
}

func (*ConflictError) registerUserRes() {}

type CreateCompanyReq struct {
	Name        string `json:"name"`
	CreditLimit int    `json:"credit_limit"`
}

// GetName returns the value of Name.
func (s *CreateCompanyReq) GetName() string {
	return s.Name
}

// GetCreditLimit returns the value of CreditLimit.
func (s *CreateCompanyReq) GetCreditLimit() int {
	return s.CreditLimit
}

// SetName sets the value of Name.
func (s *CreateCompanyReq) SetName(val string) {
	s.Name = val
}

// SetCreditLimit sets the value of CreditLimit.
func (s *CreateCompanyReq) SetCreditLimit(val int) {
	s.CreditLimit = val
}

type CreditLimit int

type Email string

// Ref: #/components/schemas/ForbiddenError
type ForbiddenError struct {
	Error   OptString `json:"error"`
	Message OptString `json:"message"`
}

// GetError returns the value of Error.
func (s *ForbiddenError) GetError() OptString {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *ForbiddenError) GetMessage() OptString {
	return s.Message
}

// SetError sets the value of Error.
func (s *ForbiddenError) SetError(val OptString) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *ForbiddenError) SetMessage(val OptString) {
	s.Message = val
}

func (*ForbiddenError) loginRes() {}

type ID int32

// Ref: #/components/schemas/InternalServerError
type InternalServerError struct {
	Error   OptString `json:"error"`
	Message OptString `json:"message"`
}

// GetError returns the value of Error.
func (s *InternalServerError) GetError() OptString {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() OptString {
	return s.Message
}

// SetError sets the value of Error.
func (s *InternalServerError) SetError(val OptString) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val OptString) {
	s.Message = val
}

func (*InternalServerError) createCompanyRes() {}
func (*InternalServerError) loginRes()         {}
func (*InternalServerError) registerUserRes()  {}

type LoginReq struct {
	Name         Name         `json:"name"`
	Email        Email        `json:"email"`
	PasswordHash PasswordHash `json:"password_hash"`
}

// GetName returns the value of Name.
func (s *LoginReq) GetName() Name {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *LoginReq) GetEmail() Email {
	return s.Email
}

// GetPasswordHash returns the value of PasswordHash.
func (s *LoginReq) GetPasswordHash() PasswordHash {
	return s.PasswordHash
}

// SetName sets the value of Name.
func (s *LoginReq) SetName(val Name) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *LoginReq) SetEmail(val Email) {
	s.Email = val
}

// SetPasswordHash sets the value of PasswordHash.
func (s *LoginReq) SetPasswordHash(val PasswordHash) {
	s.PasswordHash = val
}

type LoginResponse struct {
	// APIリクエストの際に使用するJWTアクセストークン。有効期限は短い。.
	AccessToken string `json:"accessToken"`
	// アクセストークンの有効期限が切れた際に、新しいトークンを再発行するために使用するトークン。有効期限は長い。.
	RefreshToken string `json:"refreshToken"`
}

// GetAccessToken returns the value of AccessToken.
func (s *LoginResponse) GetAccessToken() string {
	return s.AccessToken
}

// GetRefreshToken returns the value of RefreshToken.
func (s *LoginResponse) GetRefreshToken() string {
	return s.RefreshToken
}

// SetAccessToken sets the value of AccessToken.
func (s *LoginResponse) SetAccessToken(val string) {
	s.AccessToken = val
}

// SetRefreshToken sets the value of RefreshToken.
func (s *LoginResponse) SetRefreshToken(val string) {
	s.RefreshToken = val
}

func (*LoginResponse) loginRes() {}

type Name string

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type PasswordHash string

type RegisterUserReq struct {
	Name         Name         `json:"name"`
	Email        Email        `json:"email"`
	PasswordHash PasswordHash `json:"password_hash"`
}

// GetName returns the value of Name.
func (s *RegisterUserReq) GetName() Name {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *RegisterUserReq) GetEmail() Email {
	return s.Email
}

// GetPasswordHash returns the value of PasswordHash.
func (s *RegisterUserReq) GetPasswordHash() PasswordHash {
	return s.PasswordHash
}

// SetName sets the value of Name.
func (s *RegisterUserReq) SetName(val Name) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *RegisterUserReq) SetEmail(val Email) {
	s.Email = val
}

// SetPasswordHash sets the value of PasswordHash.
func (s *RegisterUserReq) SetPasswordHash(val PasswordHash) {
	s.PasswordHash = val
}

// Ref: #/components/schemas/UnauthorizedError
type UnauthorizedError struct {
	Error   OptString `json:"error"`
	Message OptString `json:"message"`
}

// GetError returns the value of Error.
func (s *UnauthorizedError) GetError() OptString {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *UnauthorizedError) GetMessage() OptString {
	return s.Message
}

// SetError sets the value of Error.
func (s *UnauthorizedError) SetError(val OptString) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *UnauthorizedError) SetMessage(val OptString) {
	s.Message = val
}

func (*UnauthorizedError) loginRes() {}

type UserResponse struct {
	ID    ID    `json:"id"`
	Name  Name  `json:"name"`
	Email Email `json:"email"`
}

// GetID returns the value of ID.
func (s *UserResponse) GetID() ID {
	return s.ID
}

// GetName returns the value of Name.
func (s *UserResponse) GetName() Name {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *UserResponse) GetEmail() Email {
	return s.Email
}

// SetID sets the value of ID.
func (s *UserResponse) SetID(val ID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *UserResponse) SetName(val Name) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *UserResponse) SetEmail(val Email) {
	s.Email = val
}

func (*UserResponse) registerUserRes() {}

// Ref: #/components/schemas/ValidationError
type ValidationError struct {
	Error   OptString `json:"error"`
	Message OptString `json:"message"`
}

// GetError returns the value of Error.
func (s *ValidationError) GetError() OptString {
	return s.Error
}

// GetMessage returns the value of Message.
func (s *ValidationError) GetMessage() OptString {
	return s.Message
}

// SetError sets the value of Error.
func (s *ValidationError) SetError(val OptString) {
	s.Error = val
}

// SetMessage sets the value of Message.
func (s *ValidationError) SetMessage(val OptString) {
	s.Message = val
}

func (*ValidationError) createCompanyRes() {}
func (*ValidationError) loginRes()         {}
func (*ValidationError) registerUserRes()  {}
