// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateBillOperation     OperationName = "CreateBill"
	CreateCompanyOperation  OperationName = "CreateCompany"
	GetBillsOperation       OperationName = "GetBills"
	GetCompanyNameOperation OperationName = "GetCompanyName"
	LoginOperation          OperationName = "Login"
	RegisterUserOperation   OperationName = "RegisterUser"
)
