// Code generated by ogen, DO NOT EDIT.
package openapi

type CreateCompanyRes interface {
	createCompanyRes()
}

type LoginRes interface {
	loginRes()
}

type RegisterUserRes interface {
	registerUserRes()
}
