// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetUser implements get User operation.
	//
	// Get the profile of the currently authenticated user.
	//
	// GET /me
	GetUser(ctx context.Context) (GetUserRes, error)
	// Login implements login operation.
	//
	// Authenticate user and return JWT token.
	//
	// POST /login
	Login(ctx context.Context, req *LoginReq) (LoginRes, error)
	// RegisterUser implements RegisterUser operation.
	//
	// Create a new user account.
	//
	// POST /register
	RegisterUser(ctx context.Context, req *RegisterUserReq) (RegisterUserRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
