// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateCompany implements CreateCompany operation.
//
// Create a new company record.
//
// POST /createcompany
func (UnimplementedHandler) CreateCompany(ctx context.Context, req *CreateCompanyReq) (r CreateCompanyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Login implements login operation.
//
// Authenticate user and return JWT token.
//
// POST /login
func (UnimplementedHandler) Login(ctx context.Context, req *LoginReq) (r LoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterUser implements RegisterUser operation.
//
// Create a new user account.
//
// POST /register
func (UnimplementedHandler) RegisterUser(ctx context.Context, req *RegisterUserReq) (r RegisterUserRes, _ error) {
	return r, ht.ErrNotImplemented
}
