// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateCompanyOperation OperationName = "CreateCompany"
	LoginOperation         OperationName = "Login"
	RegisterUserOperation  OperationName = "RegisterUser"
)
