// Code generated by ogen, DO NOT EDIT.
package openapi

type GetUserRes interface {
	getUserRes()
}

type LoginRes interface {
	loginRes()
}

type RegisterUserRes interface {
	registerUserRes()
}
