// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"net/http"
	"time"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// GetBillsParams is parameters of GetBills operation.
type GetBillsParams struct {
	// 請求書を取得する対象の日付 (YYYY-MM-DD).
	CreditDate time.Time
}

func unpackGetBillsParams(packed middleware.Parameters) (params GetBillsParams) {
	{
		key := middleware.ParameterKey{
			Name: "credit_date",
			In:   "query",
		}
		params.CreditDate = packed[key].(time.Time)
	}
	return params
}

func decodeGetBillsParams(args [0]string, argsEscaped bool, r *http.Request) (params GetBillsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: credit_date.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "credit_date",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToDate(val)
				if err != nil {
					return err
				}

				params.CreditDate = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "credit_date",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
