// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Bill struct {
	ID         int32
	Name       string
	Credit     int32
	CreditDate time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Company struct {
	ID          int32
	Name        string
	CreditLimit int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID           int32
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
